# fly.toml app configuration file generated for blue-surf-3148 on 2023-10-12T12:11:34+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blue-surf-3148"
primary_region = "arn"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.20.2"



[services]
   [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
    
   [[services.http_checks]]
    interval = "15s"  
    timeout = "2s"    
    path = "/health"  
    protocol = "http" 
    port = "5000"       

